zero_when_static: true

# The number of polls needed to be done before the device is considered "static"
static_count_threshold: 30

# Set the translational deadband
static_trans_deadband: 0.1

# Set the rotational deadband
static_rot_deadband: 0.1

# Set the scale of the linear output
linear_scale:
  - x: 1
  - y: 1
  - z: 1

# Set the scale of the angular output
angular_scale:
  - x: 1
  - y: 1
  - z: 1
