zero_when_static: true

# The number of polls needed to be done before the device is considered "static"
static_count_threshold: 30

# Set the translational deadband
static_trans_deadband: 50

# Set the rotational deadband
static_rot_deadband: 50

# For normalizing output values from SpaceMouse to [-1, 1]
full_scale: 512.0

# Only for sending UR commands
ur_linear_scale: [0.05, 0.05, 0.05]
ur_angular_scale: [0.2, 0.2, 0.2]
